### ISSUE TITLE
Adding bed file support

### ISSUE THREAD

**Issue by bilgehannevruz** [telatin/covtobed#10]
Hello,

It can be good if we can provide a bed file, to get a covered and not covered list of genes or regions.
For now, I am doing this via python however it is making the process very slow. 

Best regards,

**Comment by telatin** [comment]
Hi  @bilgehannevruz,  thanks for the feedback!
The ancestor of _covtobed_ (called 'coverage'), did this, but it's old and the source is not available for licensing issues. The binary ships with the docker image and can be used like
```
coverage -i panel_02.bam -t target_regions.bed --bed > output.bed
```

Having this said, it's in our wish list to provide this functionality, but it won't happen in the immediate future, unfortunately.

**Comment by telatin** [comment]
We are testing a new version with bed support, but release is not imminent.

For the records I drafted a Python script to merge a GTF (or BED) and a covtobed-output (BED) here: 
https://gist.github.com/telatin/82b4c51b7085dd0597659de0cf632d2a

**Comment by bilgehannevruz** [comment]
@telatin 

Thank you for the information and provided gist.

**Comment by telatin** [comment]
Quick update:
there is a "covtotarget" tool that can be applied downstream.

Info:
https://github.com/telatin/covtools/blob/master/README.md#covtotarget

Linux binary:
https://github.com/telatin/covtools/tree/master/release
