### ISSUE TITLE
Discrepancy in example output

### ISSUE THREAD

**Issue by jdeligt** [telatin/covtobed#5]
I installed through conda and ran covtobed -m 0 -x 5 test/demo.bam on the git repo;

> EMPTY	0	414	0
NC_001416.1	0	2	0
NC_001416.1	2	6	1
NC_001416.1	6	7	2
NC_001416.1	7	12	3
NC_001416.1	12	18	4
NC_001416.1	169	170	4
NC_001416.1	201	206	4
NC_001416.1	206	207	3
NC_001416.1	207	214	4
NC_001416.1	514	539	4
NC_001416.1	539	540	3
NC_001416.1	540	569	4
NC_001416.1	596	609	4
NC_001416.1	1120	1999	0
NC_001416.1	2653	2674	4
NC_001416.1	2674	2686	3
NC_001416.1	2686	2762	2
NC_001416.1	2762	2771	1
NC_001416.1	2771	2800	0

Please update the example to match what is in the repo.

**Comment by telatin** [comment]
To keep the README short, I explicited the truncation with `[...]`.

**Comment by jdeligt** [comment]
Thanks for updating it, I was mainly referring to a line that is not just missing but discordant; 
## Original
>NC_001416.1	1112	1120	4
NC_001416.1	1120	1999	0
## Actual
> NC_001416.1 596 609 4
NC_001416.1 1120 1999 0

This suggests that data has changed in the repo without the Readme being updated accordingly.
Or that functionaility changed, adding a test folder with the test output generated with the data and code in the repo can prevent things like that from happening. 
I see that you have started a README in the test output. Please include the full test output and potential output files from example commaands here and populate it with a test suite or script.

**Comment by telatin** [comment]
I added new synthetic BAM files to allow for automated tests. In particular "test_cov.bam" has reference chromosomes named after the coverage of the only peak expected (e.g. reference _5X_ is expected to produce a single BED feature of 5X coverage).

https://github.com/telatin/covtobed/wiki/Testing

**Comment by jdeligt** [comment]
All good, missed that, sorry. Thanks for that.
