### ISSUE TITLE
Please expand benchmarking

### ISSUE THREAD

**Issue by jdeligt** [telatin/covtobed#6]
In my encounters with bedtools there were quite some times when output was not correct due to ambiguities of 'when to count a read' (clipped bases, Quality of read vs base, etc.). It would be good to not only benchmark performance but also concordance.

The benchmark section could benefit from a statement of what tools were considered. i.e. Artem worked on a similar re-implementation of depth analysis in sambamba, [sambamba-depth](https://github.com/biod/sambamba/wiki/%5Bsambamba-depth%5D-documentation), was this tools considered for benchmarking?

**Comment by telatin** [comment]
Thanks for the comment, we will exapand the benchmark page.

I didn't know about sambamba-depth, do you know if it has a method to output the stats in bed format? We can add it in any case using "sambamba depth base", but the output is definitely different (per base, indeed, even if the coverage is not changing)

**Comment by telatin** [comment]
**Documentation**

The Wiki has been expanded with further details on the coverage calculation, explaining potential differences with other tools.
An output example has been added https://github.com/telatin/covtobed/blob/master/test/output/README.md including output from different tools.

**Comment by telatin** [comment]
The benchmark page now has a preamble on the choice of tools, and a link to a comparison with _sambamba-depth_: https://github.com/telatin/covtobed/tree/master/benchmark#readme
